### ISSUE TITLE
Can't compile because of missing/wrongly named unit

### ISSUE THREAD

**Issue by luebbe** [beNative/LogViewer#1]
This is the error:
[dcc32 Fataler Fehler] DDuce.Factories.zObjInspector.pas(25): F2613 Unit 'zObjInspector' nicht gefunden.

and when I open the unit, it looks like the unit references itself.

**Comment by luebbe** [comment]
Any news on this subject? I just tried to build the project again, but it still fails at the same location. How do you ever compile it?

**Comment by beNative** [comment]
Hi,

See my comment in [https://github.com/beNative/dduce/issues/3](https://github.com/beNative/dduce/issues/3)
Build instructions will be added soon. Let me know if you still experience any problems.

**Comment by luebbe** [comment]
Thanks, That helped me to compile it.
